import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Github, ExternalLink, Code2, HeartPulse, Hotel, ShoppingBag } from 'lucide-react';

const Projects = () => {
    const [filter, setFilter] = useState('All');

    const projects = [
        {
            title: 'AI Code Detector',
            description: 'An AI-powered tool built to analyze text and code snippets to determine if they were generated by artificial intelligence. Utilizes advanced NLP models.',
            imageIcon: <Code2 size={48} className="text-softBlue-500" />,
            tags: ['React', 'Node.js', 'LLM API', 'Tailwind'],
            category: 'AI',
            githubLink: '#',
            liveLink: null,
        },
        {
            title: 'Bill Buddy AI',
            description: 'A smart payment agent that helps manage personal finances, tracks bills, and predicts future expenses using AI. Live demo available for testing.',
            imageIcon: <span className="text-5xl border border-softBlue-200 dark:border-softBlue-800 rounded-full p-2 bg-softBlue-50 dark:bg-softBlue-900/30">💸</span>,
            tags: ['React', 'AI Integration', 'Express', 'MongoDB'],
            category: 'AI',
            githubLink: '#',
            liveLink: '#demo',
        },
        {
            title: 'TeleMed AI',
            description: 'A comprehensive medical assistant platform providing symptom checking, preliminary AI consultations, and appointment scheduling.',
            imageIcon: <HeartPulse size={48} className="text-softBlue-500" />,
            tags: ['PHP', 'MySQL', 'JavaScript', 'AI APIs'],
            category: 'Web',
            githubLink: '#',
            liveLink: null,
        },
        {
            title: 'Hotel Star Heaven',
            description: 'A complete hotel booking and management system featuring room availability checking, secure booking procedures, and an admin dashboard.',
            imageIcon: <Hotel size={48} className="text-softBlue-500" />,
            tags: ['Laravel', 'PHP', 'Tailwind', 'MySQL'],
            category: 'Web',
            githubLink: '#',
            liveLink: null,
        },
        {
            title: 'Jay Ambe Bag Shop',
            description: 'An engaging e-commerce platform developed for a real bag shop, showcasing products with modern UI, filtering, and a seamless checkout simulation.',
            imageIcon: <ShoppingBag size={48} className="text-softBlue-500" />,
            tags: ['React.js', 'Context API', 'CSS Styling'],
            category: 'Web',
            githubLink: '#',
            liveLink: null,
        }
    ];

    const filteredProjects = filter === 'All'
        ? projects
        : projects.filter(project => project.category === filter);

    const filters = ['All', 'Web', 'AI'];

    return (
        <section id="projects" className="py-24 bg-white dark:bg-slate-900/50 transition-colors duration-300">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">

                <div className="text-center mb-16">
                    <motion.h2
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        transition={{ duration: 0.5 }}
                        className="section-title"
                    >
                        Featured Projects
                    </motion.h2>

                    {/* Project Filtering */}
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        transition={{ duration: 0.5, delay: 0.1 }}
                        className="flex justify-center gap-4 mt-8"
                    >
                        {filters.map(f => (
                            <button
                                key={f}
                                onClick={() => setFilter(f)}
                                className={`px-6 py-2 rounded-full font-medium transition-all duration-300 ${filter === f
                                        ? 'bg-softBlue-600 text-white shadow-lg shadow-softBlue-500/30'
                                        : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-slate-700'
                                    }`}
                            >
                                {f}
                            </button>
                        ))}
                    </motion.div>
                </div>

                {/* Projects Grid */}
                <motion.div
                    layout
                    className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8"
                >
                    <AnimatePresence>
                        {filteredProjects.map((project, index) => (
                            <motion.div
                                key={project.title}
                                layout
                                initial={{ opacity: 0, scale: 0.9 }}
                                animate={{ opacity: 1, scale: 1 }}
                                exit={{ opacity: 0, scale: 0.9 }}
                                transition={{ duration: 0.4 }}
                                className="card flex flex-col h-full group"
                            >
                                {/* Decorative top section replacing image for now */}
                                <div className="h-48 bg-slate-100 dark:bg-slate-800 flex items-center justify-center relative overflow-hidden">
                                    <div className="absolute inset-0 bg-gradient-to-br from-softBlue-500/10 to-transparent"></div>
                                    <motion.div
                                        whileHover={{ scale: 1.1, rotate: 5 }}
                                        transition={{ type: "spring", stiffness: 300 }}
                                    >
                                        {project.imageIcon}
                                    </motion.div>
                                    {/* Overlay on hover */}
                                    <div className="absolute inset-0 bg-softBlue-600/90 flex flex-col items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 gap-4">
                                        <span className="text-white font-medium px-4 py-2 border border-white/30 rounded-full backdrop-blur-sm">View Details</span>
                                    </div>
                                </div>

                                <div className="p-6 flex-grow flex flex-col">
                                    <h3 className="text-xl font-bold text-slate-800 dark:text-white mb-3 group-hover:text-softBlue-600 dark:group-hover:text-softBlue-400 transition-colors">
                                        {project.title}
                                    </h3>
                                    <p className="text-slate-600 dark:text-slate-400 mb-6 flex-grow text-sm leading-relaxed">
                                        {project.description}
                                    </p>

                                    {/* Tags */}
                                    <div className="flex flex-wrap gap-2 mb-6">
                                        {project.tags.map(tag => (
                                            <span key={tag} className="text-xs font-medium px-2.5 py-1 bg-softBlue-50 text-softBlue-600 dark:bg-softBlue-900/30 dark:text-softBlue-400 rounded-md">
                                                {tag}
                                            </span>
                                        ))}
                                    </div>

                                    {/* Links */}
                                    <div className="pt-4 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between">
                                        <a
                                            href={project.githubLink}
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            className="flex items-center gap-2 text-sm font-medium text-slate-600 hover:text-slate-900 dark:text-slate-400 dark:hover:text-white transition-colors"
                                        >
                                            <Github size={18} />
                                            Code
                                        </a>

                                        {project.liveLink ? (
                                            <a
                                                href={project.liveLink}
                                                target="_blank"
                                                rel="noopener noreferrer"
                                                className="flex items-center gap-2 text-sm font-medium text-softBlue-600 hover:text-softBlue-700 dark:text-softBlue-400 dark:hover:text-softBlue-300 transition-colors"
                                            >
                                                Live Demo
                                                <ExternalLink size={18} />
                                            </a>
                                        ) : (
                                            <span className="text-xs text-slate-400 dark:text-slate-500 italic">Code on GitHub</span>
                                        )}
                                    </div>
                                </div>
                            </motion.div>
                        ))}
                    </AnimatePresence>
                </motion.div>

            </div>
        </section>
    );
};

export default Projects;
